specVersion: 0.0.1 # not used for now
org: zb # required, usually this should be company name without space.
kind: ethereum
version: 0 # not used for now
#name: demo # required
network: holesky
initialization:
  initializationHandlers: # used to initialize pg, which can be done manually too
    - HandleInitialization
source:
  schema: "ethereum_holesky"
  sourceDB: RDS_PROD_DB
  startBlock: 1187561
metadata:
  metadataDB: RDS_TEST_DB
destination:
  destinationDB: RDS_TEST_DB
  schema: public
eventHandlers: # multiple handlers
  - event: AVSMetadataURIUpdated
    handler: HandleAVSMetadataURIUpdated
  - event: OperatorAVSRegistrationStatusUpdated
    handler: HandleOperatorAVSRegistrationStatusUpdated
blockHandlers:
  - handler: HandleBlock