name: zrunner trigger

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event type'
        required: true
        default: 'eigenlayer_build'
  push:
    branches:
      - "main"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Zettablock/zrunner/dispatches \
            -d '{"event_type":"${{ github.event.inputs.event_type }}","client_payload":{"unit":false,"integration":true}}'
